exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex("house")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("house").insert([
        {
          "houseId": 1,
          "userId": 1,
          "name": "NhaTro1",
          "address": "120 Hoàng Đạo Thành",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro1-1618037718826-house.jpg",
        },
        {
          "houseId": 2,
          "userId": 2,
          "name": "NhaTro2",
          "address": "120 Kim Giang",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro2-1618037718826-house.jpg",
        },
        {
          "houseId": 3,
          "userId": 3,
          "name": "NhaTro3",
          "address": "120 Định Công",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro3-1618037718826-house.jpg",
        },
        {
          "houseId": 4,
          "userId": 4,
          "name": "NhaTro4",
          "address": "120 Vũ Tông Phan",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Thanh Xuân",
          "ward": "Khương Đình",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro4-1618037718826-house.jpg",
        },
        {
          "houseId": 5,
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
        {
          "userId": 5,
          "name": "NhaTro5",
          "address": "120 Nguyễn Xiển",
          "status": "Hoạt động",
          "province": "Thành phố Hà Nội",
          "district": "Quận Hoàng Mai",
          "ward": "Phường Đại Kim",
          "description":
            "Nhà trọ đầy đủ tiện nghi, điện nước giá rẻ, CÒN PHÒNG.",
          "image": "uploads/images/IMAGE-ChuTro5-1618037718826-house.jpg",
        },
      ]);
    });
};
